import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>OTP Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          OTP Server
        </h1>

        <p className={styles.description}>
          API endpoint: /api/otp
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Generate OTP</h2>
            <p>{'/api/otp/generate?user={user}'}</p>
          </div>          

          <div className={styles.card}>
            <h2>Verify OTP</h2>
            <p>{'/api/otp/verify?user={user}&otp={otp}'}</p>
          </div> 
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
